name: release

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11
          cache: "maven"

      - name: Deploy with Maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
