name: verify

concurrency:
  group: verify
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11
          cache: "maven"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
